# .streamlit/config.toml

[theme]
base="light"
primaryColor="#3399ff"
backgroundColor="#eaf6ff"
secondaryBackgroundColor="#eaf6ff"
textColor="#003366"
font="sans serif" # יכול להיות גם "serif", "monospace" או שם של גופן מותאם