# .streamlit/config.toml
[theme]
base="light"
primaryColor="#FFB3BA"  # ורוד פסטל
backgroundColor="#FFFFE0"  # קרם בהיר מאוד
secondaryBackgroundColor="#E0F4C1"  # ירוק בהיר מאוד
textColor="#333333"  # אפור כהה
font="sans serif"