# .streamlit/config.toml
[theme]
base="light"
primaryColor="#1E90FF"  # כחול דודג'ר - כחול בהיר וחי עבור אלמנטים ראשיים (כפתורים, הדגשים)
backgroundColor="#F0F8FF"  # כחול אליס בהיר מאוד - רקע כללי בהיר
secondaryBackgroundColor="#E6F2FA"  # כחול כהה יותר, עבור סיידבאר ובלוקים משניים
textColor="#4682B4"  # כחול פלדה - צבע טקסט כללי, כהה מספיק לקריאות
font="sans serif"