[theme]
base="light"
primaryColor="#6B8EAD"  # כחול מעושן (Dusty Blue)
backgroundColor="#FAF9F6"  # לבן-שנהב / אוף-ווייט (Off-white / Eggshell)
secondaryBackgroundColor="#E9ECEF"  # אפור בהיר מאוד (Light Gray)
textColor="#3E5060"  # כחול-אפור כהה (Dark Slate Gray/Blue)
font="sans serif"