# .streamlit/config.toml
[theme]
# מצב כללי
base                      = "light"

# פלטת-צבעים ­– מסודרת על-פי שימוש
primaryColor              = "#B08D57"   # זהב מושתק (כפתורי פעולה / לינקים)
backgroundColor           = "#FBF5EF"   # בז'-קרם (רקע כללי)
secondaryBackgroundColor  = "#FCFCFC"   # לבן-שקט (כרטיסים / בלוקים)
textColor                 = "#4A3B31"   # חום כהה (טקסט)

# טיפוגרפיה
font                      = "sans serif"  # אפשר לשנות ל-"serif" או "monospace" לפי צורךתאמה נוספת ב-CSS